In [1]:
import numpy as np

In [2]:
def f(x):
    """the right-hand side of the differential equation"""
    return 6 * np.pi * np.cos(3 * np.pi * x) - 9 * (np.pi**2) * x * np.sin(
        3 * np.pi * x
    )

In [3]:
def u(x):
    """the exact solution of the differential equation"""
    return x * np.sin(3 * np.pi * x)

In [4]:
def gen_val(n, h, a, y):
    """generate the values of the function y at the points x_i"""
    y = np.zeros(n - 1)
    for i in range(n - 1):
        y[i] = -u(a + (i + 1) * h) * (h**2)
    return y

In [5]:
def gen_A(n):
    """generate the matrix A of the linear system of equations Au=p"""
    n = n - 1
    A = np.zeros((n, n))
    for i in range(n):
        A[i, i] = -2
        if i > 0:
            A[i, i - 1] = 1
        if i < n - 1:
            A[i, i + 1] = 1
    return A


gen_A(5)

array([[-2.,  1.,  0.,  0.],
       [ 1., -2.,  1.,  0.],
       [ 0.,  1., -2.,  1.],
       [ 0.,  0.,  1., -2.]])

In [6]:
def gen_p(n, h, f, a, b):
    """generate the vector p of the linear system of equations Au=p"""
    p = np.zeros((n - 1, 1))
    p[0] = -(h**2) * f[0] - a
    for i in range(1, n - 2):
        p[i] = -(h**2) * f[i]
    p[n - 2] = -(h**2) * f[n - 2] - b
    return p

In [7]:
def gen_matrix(n, h, a, b):
    """
    generate the matrix A and the vector p of the linear system of equations Au=p
    Parameters:
    n: number of intervals
    h: step size
    a: u(0)
    b: u(1)
    """
    A = gen_A(n)
    f_ls = gen_val(n, h, a, f)
    p = gen_p(n, h, f_ls, a, b)
    return A, p

In [18]:
def richardson(A, p, a_k, tol=1e-10, max_iter=100000):
    """
    solve the linear system of equations Au=p using the Richardson iteration method
    Parameters:
    A: matrix A
    p: vector p
    tol: tolerance
    max_iter: maximum number of iterations
    """
    x = np.zeros((A.shape[0], 1))
    for i in range(max_iter):
        r = p - A @ x
        if i % 1000 == 0:
            print(np.linalg.norm(r))
        if np.linalg.norm(r) < tol:
            print(i)
            print("converged")
            break
        if True in np.isnan(x):
            print("x contains nan", i)
            break
        x = x + a_k * r
    return x

In [9]:
def eigenval_k(k, n):
    """
    calculate the spectral radius of the matrix A
    """
    return 4 * n**2 * (np.sin(np.pi * k / (2 * n))) ** 2

In [10]:
def eigenvals(n):
    """
    calculate the eigenvalues of the matrix A
    """

    return np.array([eigenval_k(k, n) for k in range(1, n)])

In [19]:
a = 0
b = 0
n_ls = np.array([8, 16, 32, 64, 128, 256])
h_ls = np.array([1 / i for i in n_ls])

n = 8
A, p = gen_matrix(n, np.float32(1 / n), a, b)
richardson(-A, p, 0.004)

0.00027912631504627296
9.232777070836018e-06
8.686013703663889e-07
8.31703137539105e-08
7.964504503845013e-09
7.626925156004891e-10
5867
converged


array([[ 9.24830335e-06],
       [-9.69799357e-06],
       [-7.18027126e-05],
       [-9.88717521e-05],
       [-3.87047917e-06],
       [ 1.49523685e-04],
       [ 1.73442786e-04]])

In [12]:
1/np.max(eigenvals(8))

np.float64(0.004060805194908516)

In [13]:
np.zeros((A.shape[0],1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [14]:
2/np.max(np.abs(np.linalg.eigvals(A))) * 0.9

np.float64(0.467804758453461)